# Generated by Django 4.1.7 on 2023-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('re_password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Try',
            },
        ),
    ]
